name: CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: "CI"

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app
      - name: Build & Tests
        run: |
          xcodebuild clean build test -scheme HUDHero \
          -sdk iphonesimulator17.5 \
          -destination "OS=17.5,name=iPhone 15 Pro" \
          -resultBundlePath HUDHero.xcresult
      - name: Display test results
        uses: jobearrr/xcresulttool@v1
        with:
          path: HUDHero.xcresult
          token: ${{ secrets.GITHUB_TOKEN }}
        if: success() || failure()
