name: Main

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: "Main"

jobs:
  test-and-gather-test-coverage:
    runs-on: macos-13
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v

    - name: Test & publish code coverage to Code Climate
      uses: paambaati/codeclimate-action@v8.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: swift test -v --enable-code-coverage
        debug: true
        coverageLocations: |
          ${{github.workspace}}/.build/debug/codecov/*.json:lcov-json
